BEGIN;

CREATE OR REPLACE FUNCTION public.set_updated_timestamp()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.mtime = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_ctime_timestamp()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.ctime = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.tb_user_info (
    uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    passcode CHAR(12) NOT NULL DEFAULT '',
    passwd CHAR(64) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 0,
    hardware VARCHAR(64) NOT NULL DEFAULT '',
    ctime TIMESTAMPTZ NOT NULL DEFAULT TIMESTAMPTZ '2013-03-15 14:38:09+00',
    mtime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tb_login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid BIGINT NOT NULL DEFAULT 0,
    state SMALLINT NOT NULL DEFAULT 0,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(31) NOT NULL DEFAULT '',
    hardware VARCHAR(64) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.tb_login_last (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid BIGINT NOT NULL DEFAULT 0 UNIQUE,
    login_time TIMESTAMPTZ,
    logout_time TIMESTAMPTZ,
    ip VARCHAR(31) NOT NULL DEFAULT '',
    is_logout SMALLINT NOT NULL DEFAULT 0,
    session VARCHAR(100),
    hardware VARCHAR(64) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.tb_role_1 (
    rid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid BIGINT NOT NULL,
    "headId" BIGINT NOT NULL DEFAULT 0,
    sex SMALLINT NOT NULL DEFAULT 0,
    nick_name VARCHAR(100),
    balance BIGINT NOT NULL DEFAULT 0,
    login_time TIMESTAMPTZ,
    logout_time TIMESTAMPTZ,
    profile VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (uid, nick_name)
);

CREATE TABLE IF NOT EXISTS public.tb_map_role_city_1 (
    "cityId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL,
    x BIGINT NOT NULL,
    y BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL DEFAULT 'Thành trì',
    is_main SMALLINT NOT NULL DEFAULT 0,
    cur_durable BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    occupy_time TIMESTAMPTZ DEFAULT TIMESTAMPTZ '2013-03-15 14:38:09+00'
);

CREATE TABLE IF NOT EXISTS public.tb_map_role_build_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL,
    type BIGINT NOT NULL,
    level SMALLINT NOT NULL,
    op_level SMALLINT,
    x BIGINT NOT NULL,
    y BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    max_durable BIGINT NOT NULL,
    cur_durable BIGINT NOT NULL,
    end_time TIMESTAMPTZ DEFAULT TIMESTAMPTZ '2013-03-15 14:38:09+00',
    occupy_time TIMESTAMPTZ DEFAULT TIMESTAMPTZ '2013-03-15 14:38:09+00',
    "giveUp_time" BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.tb_city_facility_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cityId" BIGINT NOT NULL UNIQUE,
    rid BIGINT NOT NULL,
    facilities VARCHAR(4096) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tb_role_res_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL UNIQUE,
    wood BIGINT NOT NULL,
    iron BIGINT NOT NULL,
    stone BIGINT NOT NULL,
    grain BIGINT NOT NULL,
    gold BIGINT NOT NULL,
    decree BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tb_general_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL,
    "cfgId" BIGINT NOT NULL,
    physical_power BIGINT NOT NULL,
    exp BIGINT NOT NULL,
    "order" SMALLINT NOT NULL,
    level SMALLINT NOT NULL DEFAULT 1,
    "cityId" BIGINT NOT NULL DEFAULT 0,
    star BIGINT NOT NULL DEFAULT 0,
    star_lv BIGINT NOT NULL DEFAULT 0,
    arms BIGINT NOT NULL DEFAULT 0,
    has_pr_point BIGINT NOT NULL DEFAULT 0,
    use_pr_point BIGINT NOT NULL DEFAULT 0,
    attack_distance BIGINT NOT NULL DEFAULT 0,
    force_added BIGINT NOT NULL DEFAULT 0,
    strategy_added BIGINT NOT NULL DEFAULT 0,
    defense_added BIGINT NOT NULL DEFAULT 0,
    speed_added BIGINT NOT NULL DEFAULT 0,
    destroy_added BIGINT NOT NULL DEFAULT 0,
    "parentId" BIGINT NOT NULL DEFAULT 0,
    compose_type BIGINT NOT NULL DEFAULT 0,
    skills VARCHAR(64) NOT NULL DEFAULT '[0, 0, 0]',
    state SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tb_army_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL,
    "cityId" BIGINT NOT NULL,
    "order" SMALLINT NOT NULL DEFAULT 0,
    generals VARCHAR(256) NOT NULL DEFAULT '[0, 0, 0]',
    soldiers VARCHAR(256) NOT NULL DEFAULT '[0, 0, 0]',
    conscript_times VARCHAR(256) NOT NULL DEFAULT '[0, 0, 0]',
    conscript_cnts VARCHAR(256) NOT NULL DEFAULT '[0, 0, 0]',
    cmd SMALLINT NOT NULL DEFAULT 0,
    from_x BIGINT NOT NULL,
    from_y BIGINT NOT NULL,
    to_x BIGINT,
    to_y BIGINT,
    start TIMESTAMPTZ,
    "end" TIMESTAMPTZ,
    UNIQUE (rid, "cityId", "order")
);

CREATE TABLE IF NOT EXISTS public.tb_war_report_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    a_rid BIGINT NOT NULL,
    d_rid BIGINT NOT NULL DEFAULT 0,
    b_a_army VARCHAR(512) NOT NULL,
    b_d_army VARCHAR(512) NOT NULL,
    e_a_army VARCHAR(512) NOT NULL,
    e_d_army VARCHAR(512) NOT NULL,
    b_a_general VARCHAR(512) NOT NULL,
    b_d_general VARCHAR(512) NOT NULL,
    e_a_general VARCHAR(512) NOT NULL,
    e_d_general VARCHAR(512) NOT NULL,
    rounds VARCHAR(10240) NOT NULL,
    result SMALLINT NOT NULL DEFAULT 0,
    a_is_read SMALLINT NOT NULL DEFAULT 0,
    d_is_read SMALLINT NOT NULL DEFAULT 0,
    destroy BIGINT,
    occupy SMALLINT NOT NULL DEFAULT 0,
    x BIGINT,
    y BIGINT,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tb_coalition_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    members VARCHAR(2048) NOT NULL,
    create_id BIGINT NOT NULL,
    chairman BIGINT NOT NULL,
    vice_chairman BIGINT NOT NULL,
    notice VARCHAR(256),
    state SMALLINT NOT NULL DEFAULT 1,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tb_coalition_apply_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    union_id BIGINT NOT NULL,
    rid BIGINT NOT NULL,
    state SMALLINT NOT NULL DEFAULT 0,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tb_role_attribute_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL,
    parent_id SMALLINT NOT NULL DEFAULT 0,
    collect_times SMALLINT NOT NULL DEFAULT 0,
    last_collect_time TIMESTAMPTZ DEFAULT TIMESTAMPTZ '2013-03-15 14:38:09+00',
    pos_tags VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS public.tb_coalition_log_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    union_id BIGINT NOT NULL,
    op_rid BIGINT NOT NULL,
    target_id BIGINT,
    des VARCHAR(256) NOT NULL,
    state SMALLINT NOT NULL,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tb_skill_1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rid BIGINT NOT NULL,
    "cfgId" BIGINT NOT NULL,
    belong_generals VARCHAR(256) NOT NULL DEFAULT '[]',
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_history_uid ON public.tb_login_history (uid);
CREATE INDEX IF NOT EXISTS idx_map_role_city_rid ON public.tb_map_role_city_1 (rid);
CREATE INDEX IF NOT EXISTS idx_map_role_build_rid ON public.tb_map_role_build_1 (rid);
CREATE INDEX IF NOT EXISTS idx_general_rid ON public.tb_general_1 (rid);
CREATE INDEX IF NOT EXISTS idx_army_rid ON public.tb_army_1 (rid);
CREATE INDEX IF NOT EXISTS idx_war_report_attack ON public.tb_war_report_1 (a_rid);
CREATE INDEX IF NOT EXISTS idx_war_report_defense ON public.tb_war_report_1 (d_rid);
CREATE INDEX IF NOT EXISTS idx_coalition_apply_union ON public.tb_coalition_apply_1 (union_id);
CREATE INDEX IF NOT EXISTS idx_coalition_apply_rid ON public.tb_coalition_apply_1 (rid);

DROP TRIGGER IF EXISTS trg_user_info_mtime ON public.tb_user_info;
CREATE TRIGGER trg_user_info_mtime
BEFORE UPDATE ON public.tb_user_info
FOR EACH ROW EXECUTE FUNCTION public.set_updated_timestamp();

DROP TRIGGER IF EXISTS trg_login_history_ctime ON public.tb_login_history;
CREATE TRIGGER trg_login_history_ctime
BEFORE UPDATE ON public.tb_login_history
FOR EACH ROW EXECUTE FUNCTION public.set_ctime_timestamp();

DROP TRIGGER IF EXISTS trg_war_report_ctime ON public.tb_war_report_1;
CREATE TRIGGER trg_war_report_ctime
BEFORE UPDATE ON public.tb_war_report_1
FOR EACH ROW EXECUTE FUNCTION public.set_ctime_timestamp();

DROP TRIGGER IF EXISTS trg_coalition_ctime ON public.tb_coalition_1;
CREATE TRIGGER trg_coalition_ctime
BEFORE UPDATE ON public.tb_coalition_1
FOR EACH ROW EXECUTE FUNCTION public.set_ctime_timestamp();

DROP TRIGGER IF EXISTS trg_coalition_apply_ctime ON public.tb_coalition_apply_1;
CREATE TRIGGER trg_coalition_apply_ctime
BEFORE UPDATE ON public.tb_coalition_apply_1
FOR EACH ROW EXECUTE FUNCTION public.set_ctime_timestamp();

DROP TRIGGER IF EXISTS trg_coalition_log_ctime ON public.tb_coalition_log_1;
CREATE TRIGGER trg_coalition_log_ctime
BEFORE UPDATE ON public.tb_coalition_log_1
FOR EACH ROW EXECUTE FUNCTION public.set_ctime_timestamp();

DROP TRIGGER IF EXISTS trg_skill_ctime ON public.tb_skill_1;
CREATE TRIGGER trg_skill_ctime
BEFORE UPDATE ON public.tb_skill_1
FOR EACH ROW EXECUTE FUNCTION public.set_ctime_timestamp();

COMMENT ON TABLE public.tb_user_info IS 'Thông tin tài khoản người chơi';
COMMENT ON TABLE public.tb_role_1 IS 'Thông tin nhân vật người chơi';
COMMENT ON TABLE public.tb_map_role_city_1 IS 'Thành trì của người chơi';
COMMENT ON TABLE public.tb_general_1 IS 'Danh sách võ tướng';
COMMENT ON TABLE public.tb_army_1 IS 'Đội quân của người chơi';
COMMENT ON TABLE public.tb_war_report_1 IS 'Báo cáo chiến đấu';
COMMENT ON TABLE public.tb_coalition_1 IS 'Liên minh';

COMMIT;
